### ISSUE TITLE
Why don't you make it a package, so that your code get recognized in mine?

### ISSUE THREAD

**Issue by mhmodzoka** [jishnub/WignerD.jl#9]
If you make the module, please make the function "wignerdjmn" accessible.

**Comment by mhmodzoka** [comment]
If you make the module, please make the function "wignerdjmn" accessible.

**Comment by mhmodzoka** [comment]
I just found it here:
https://juliahub.com/ui/Packages/WignerD/J6Hjz/0.1.2?t=0

And it can be installed with

`using Pkg; Pkg.add("WignerD")`

**Comment by jishnub** [comment]
I'm sorry I had somehow missed your comment, hope you have found this useful
